spring.application.name=backend
server.port=8082
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

springdoc.default-produces-media-type=application/json
jwt.secret=ReplaceThisWithAReal256BitSecretKeyForDevelopmentOnly12345
jwt.expiration=86400000
# ==========================
# Database Configuration
# ==========================

spring.datasource.url=jdbc:postgresql://localhost:5432/libracore_db
spring.datasource.username=postgres
spring.datasource.password=Megh@67A1

spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=YourVeryLongSecretKeyMustBeAtLeast32CharactersLongForHS256Signing
jwt.expiration=86400000

# ==========================
# JPA Configuration
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect